remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Jacob Senior ePortfolio
email: jacobsen2601@gmail.com
name: Jacob Senior<hr>Software Engineer
linkedin: www.linkedin.com/in/jacobsenior326
