remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Jacob Senior ePortfolio
logo: /Gallery/JacobSeniorHeadshot.png
email: jacobsen2601@gmail.com
name: Jacob Senior<br>Software Engineer
linkedin: www.linkedin.com/in/jacobsenior326
show_downloads: true
resume:
  docx_url: Resume/Jacob_Senior_Software_Engineer_Resume.docx
  pdf_url: Resume/Jacob_Senior_Software_Engineer_Resume.pdf
  github_url: https://github.com/jsenior326/jsenior326.github.io/blob/main/Resume/Jacob_Senior_Software_Engineer_Resume.pdf
